seed: 1
models:
  separate: false
  policy:
    class: GaussianMixin
    clip_actions: false
    clip_log_std: true
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
    - name: net
      input: STATES
      layers:
      - 256
      - 256
      - 256
      activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: false
    network:
    - name: net
      input: STATES
      layers:
      - 256
      - 256
      - 256
      activations: elu
    output: ONE
memory:
  class: RandomMemory
  memory_size: -1
agent:
  class: PPO
  rollouts: 24
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0001
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
    max_lr: 0.0003
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: true
  entropy_loss_scale: 0.001
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 0.6
  time_limit_bootstrap: false
  experiment:
    directory: /home/donglei/isaac_projects/isaac_drone_racer/.worktrees/stage1-fake-vio/logs/skrl/stage1_recovery_20260905/2026-09-05_11-37-52
    experiment_name: 2026-09-05_11-37-57_ppo_torch_stage1_mixed
    write_interval: auto
    checkpoint_interval: auto
trainer:
  class: SequentialTrainer
  timesteps: 50400
  environment_info: log
  close_environment_at_exit: false
